using System.Globalization;
using ClosedXML.Excel;
using Document_Management.Models;

namespace Document_Management.Service
{
    public sealed class ReportExcelExportService
    {
        private static readonly DateOnly MinimumExcelDate = new(1900, 1, 1);

        public byte[] GenerateFileUploadReport(
            DateOnly dateFrom,
            DateOnly dateTo,
            string generatedBy,
            IReadOnlyCollection<FileUploadReportViewModel> uploadedFiles)
        {
            using var workbook = new XLWorkbook();
            var worksheet = workbook.Worksheets.Add("File Upload Report");

            worksheet.Cell(1, 1).Value = "FILE UPLOAD REPORT";
            worksheet.Range(1, 1, 1, 10).Merge();
            worksheet.Cell(2, 1).Value = $"Date Range: {dateFrom:MMM dd, yyyy} to {dateTo:MMM dd, yyyy}";
            worksheet.Range(2, 1, 2, 10).Merge();
            worksheet.Cell(3, 1).Value = $"Generated by: {generatedBy}";
            worksheet.Range(3, 1, 3, 10).Merge();

            var title = worksheet.Range(1, 1, 1, 10);
            title.Style.Font.Bold = true;
            title.Style.Font.FontSize = 16;
            title.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;

            string[] headers =
            [
                "Box #",
                "Company",
                "Year",
                "Department",
                "Category",
                "Sub Category",
                "User",
                "Files",
                "Submitted By",
                "Date"
            ];

            const int headerRow = 5;
            for (var column = 1; column <= headers.Length; column++)
            {
                worksheet.Cell(headerRow, column).Value = headers[column - 1];
            }

            var header = worksheet.Range(headerRow, 1, headerRow, headers.Length);
            header.Style.Font.Bold = true;
            header.Style.Font.FontColor = XLColor.White;
            header.Style.Fill.BackgroundColor = XLColor.FromHtml("#6C757D");
            header.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;

            var row = headerRow + 1;
            foreach (var fileGroup in uploadedFiles)
            {
                worksheet.Cell(row, 1).Value = fileGroup.BoxNumber;
                worksheet.Cell(row, 2).Value = fileGroup.Company;
                worksheet.Cell(row, 3).Value = fileGroup.Year;
                worksheet.Cell(row, 4).Value = fileGroup.Department;
                worksheet.Cell(row, 5).Value = fileGroup.Category;
                worksheet.Cell(row, 6).Value = fileGroup.SubCategory;
                worksheet.Cell(row, 7).Value = fileGroup.Username;
                worksheet.Cell(row, 8).Value = fileGroup.FileCount;
                worksheet.Cell(row, 9).Value = fileGroup.SubmittedBy;

                if (fileGroup.DateSubmitted.HasValue)
                {
                    var dateSubmitted = fileGroup.DateSubmitted.Value;
                    worksheet.Cell(row, 10).Value = dateSubmitted >= MinimumExcelDate
                        ? dateSubmitted.ToDateTime(TimeOnly.MinValue)
                        : dateSubmitted.ToString("MMM dd, yyyy", CultureInfo.InvariantCulture);
                }

                row++;
            }

            if (uploadedFiles.Count > 0)
            {
                var dataRange = worksheet.Range(headerRow, 1, row - 1, headers.Length);
                dataRange.Style.Border.OutsideBorder = XLBorderStyleValues.Thin;
                dataRange.Style.Border.InsideBorder = XLBorderStyleValues.Thin;
                dataRange.SetAutoFilter();
                worksheet.Range(headerRow + 1, 8, row - 1, 8).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                worksheet.Range(headerRow + 1, 10, row - 1, 10).Style.DateFormat.Format = "mmm dd, yyyy";
            }

            worksheet.SheetView.FreezeRows(headerRow);
            worksheet.Columns(1, headers.Length).AdjustToContents();

            for (var column = 1; column <= headers.Length; column++)
            {
                if (worksheet.Column(column).Width > 30)
                {
                    worksheet.Column(column).Width = 30;
                }
            }

            using var stream = new MemoryStream();
            workbook.SaveAs(stream);
            return stream.ToArray();
        }
    }
}
